### ISSUE TITLE
[Task]:  Setup scripts to populate the search index from the DB

### ISSUE THREAD

**Issue by chouinar** [navapbc/simpler-grants-gov#10]
### Summary

- Should be usable in a non-script way (ie. functions we can call with specific opportunity records - we’ll use it for tests as well)
- Should only load records that aren’t drafts + have an opportunity status
- Should make a new index with configurable values (number of shards)
- Should setup an alias
- Should use bulk uploads for performance
- https://opensearch.org/docs/latest/im-plugin/index-templates/ 
-

**Comment by acouch** [comment]
Issue migrated to hhs/simpler-grants-gov#2092
