### ISSUE TITLE
[Task]: Cleanup / refactor transformation work to be less boilerplatey

### ISSUE THREAD

**Issue by chouinar** [navapbc/simpler-grants-gov#104]
### Summary

The transformation work was written quickly and thus a lot of the implementation is clunky and repetitive. We should take a pass at refactoring it to cleanup a lot of these issues.

We should timebox this effort as there is always more that can be refactored in complex code bases.

**Comment by acouch** [comment]
Issue migrated to hhs/simpler-grants-gov#2054
