### ISSUE TITLE
[Task]: Add transformation for agency data

### ISSUE THREAD

**Issue by chouinar** [navapbc/simpler-grants-gov#106]
### Summary

See: https://docs.google.com/document/d/1EPZJyqTQruq-BkQoojtrkLqgVl8GrpfsZAIY9T1dEg8/edit#heading=h.9a4loabrp0a3  for details on these tables

**Comment by acouch** [comment]
Issue migrated to hhs/simpler-grants-gov#2051

**Comment by acouch** [comment]
Issue migrated to hhs/simpler-grants-gov#2053
