### ISSUE TITLE
[Task]:  Setup test utilities for the search index

### ISSUE THREAD

**Issue by chouinar** [navapbc/simpler-grants-gov#11]
### Summary

- Using whatever this script: https://github.com/navapbc/simpler-grants-gov/issues/10
- See if there is a reasonable way to use our factories directly so we don’t need to load from the DB every time.
- Create / delete indexes in pytest fixtures so we don’t have a bunch of orphaned indexes

**Comment by chouinar** [comment]
Merging this work into https://github.com/navapbc/simpler-grants-gov/issues/10

**Comment by chouinar** [comment]
Merging this work into https://github.com/navapbc/simpler-grants-gov/issues/10

**Comment by acouch** [comment]
Issue migrated to hhs/simpler-grants-gov#2090
