### ISSUE TITLE
[Task]: Remove Dynaconf from Analytics

### ISSUE THREAD

**Issue by aplybeah** [navapbc/simpler-grants-gov#115]
### Summary

After getting feedback for #107, the consensus was to reevaluate the way the database loader works for more uniformity. Changes will need to be made primarily in `db.py` and `cli.py`

### Acceptance criteria

- [ ] `Dynaconf` and related files removed
- [ ] Database connections work as expected
- [ ] Integrations such as Slack and Github work as expected

**Comment by acouch** [comment]
Issue migrated to hhs/simpler-grants-gov#2057
