### ISSUE TITLE
Research GitHub Migration

### ISSUE THREAD

**Issue by margaretspring** [navapbc/simpler-grants-gov#116]

**Comment by margaretspring** [comment]
What will be necessary to migrate the NavaPBC/Simpler Sprint Repository and Board into the HHS Repository. 

Some notes for initial regroup with HHS [here.](https://docs.google.com/document/d/1R5Uqo6UsPnBu4pSutteCaygH4LmnqkT5H-XcicxPxD8/edit#heading=h.c6pf5u1omfic)

**Comment by acouch** [comment]
Issue migrated to hhs/simpler-grants-gov#2133
