### ISSUE TITLE
[Task]:  Setup a new search endpoint (V1?)

### ISSUE THREAD

**Issue by chouinar** [navapbc/simpler-grants-gov#12]
### Summary

- Should copy the v0.1 endpoint and schema
- Delete all of the implementation of the search queries to the DB and return a static (empty?) list for the moment
- We'll fill this in later, this is just a lot of boilerplate, easier to do separate from an actual implementation

**Comment by acouch** [comment]
Issue migrated to hhs/simpler-grants-gov#2093
