### ISSUE TITLE
10K - OPP: Opportunity Listing Service Blueprint

### ISSUE THREAD

**Issue by margaretspring** [navapbc/simpler-grants-gov#129]
Leverage [Service Blueprint](https://navasage.atlassian.net/wiki/spaces/NH/pages/421232641/Toolkit+Service+Blueprinting+Guide) approach to conduct discovery to be utilized across upcoming Opportunity work.

**Comment by acouch** [comment]
Issue migrated to hhs/simpler-grants-gov#2121
