### ISSUE TITLE
[Task]:  Setup client connection for calling OpenSearch

### ISSUE THREAD

**Issue by chouinar** [navapbc/simpler-grants-gov#13]
### Summary

Use https://opensearch.org/docs/latest/clients/python-low-level/

- Should have a config class that loads the env vars
- Should figure out how we'll use this in the API (re-create every time? long-lived?) and implement it to be fetched in the search endpoint (no querying yet though)

**Comment by chouinar** [comment]
Merging this work into https://github.com/navapbc/simpler-grants-gov/issues/10

**Comment by acouch** [comment]
Issue migrated to hhs/simpler-grants-gov#2087
