### ISSUE TITLE
[Task]: Update analytics documentation to reflect metabase and analytics database and deemphasize slack and metric calculation

### ISSUE THREAD

**Issue by acouch** [navapbc/simpler-grants-gov#131]
### Summary

The current analytics readme and docs focuses on the previous version of the tool. It should be rewritten to reflect the recent changes.

It should highlight the fact that we have moved to capturing analytics in a postgres analytics database that will house our future analytics data and that we will use Metabase as a analyses and dashboard tool. It should highlight that system is architected so that the analytics work that will be part of the project can be run locally, though it is housed in AWS.

### Acceptance criteria

- [ ] [README.md](https://github.com/navapbc/simpler-grants-gov/blob/main/analytics/README.md#simpler-grants-analytics) should be updated.
  * The [introduction](https://github.com/navapbc/simpler-grants-gov/blob/main/analytics/README.md#simpler-grants-analytics) should reflect the goals and structure noted above. Bonus points if it can link to the [architecture diagram](https://github.com/navapbc/simpler-grants-gov/blob/main/documentation/architecture/README.md#aws-hosted-infrastructure) and if a separate diagram can be created to show the metabase -> analytics database <- ECS python service. 
  *   The [directory structure](https://github.com/navapbc/simpler-grants-gov/blob/main/analytics/README.md#project-directory-structure) should be updated or removed
  *  An "Data Pipeline Service" section should be written that explains the python portion
  *  A sub-section of "Data Pipeline" should include "Current Data" section that describes the current data and its structure 
  *  [Using the tool](https://github.com/navapbc/simpler-grants-gov/blob/main/analytics/README.md#using-the-tool) should be renamed "Using the Slack Tool" or something, and a "Local Development" section be written with quick instructions to start the tool and run github report, ie 1. *start the containers* `make start` 1a. setup the github login or token 2. *export the current data*`make sprint-data-export && make issue-data-export` 3. *import the data* `make sprint-db-data-import` and 4. *view the data in metabase* ie go to localhost:3100
  *   * 
- [ ] [Technical Overview](https://github.com/navapbc/simpler-grants-gov/blob/main/documentation/analytics/technical-overview.md) should be updated. The "Key Technologies" section could be updated to reflect that this is just the "Data pipeline service" part of the analytics.  The "Orchestration" section should be be updated to include correct links https://github.com/navapbc/simpler-grants-gov/blob/main/documentation/analytics/technical-overview.md#orchestration
- [ ] [development.md](https://github.com/navapbc/simpler-grants-gov/blob/main/documentation/analytics/development.md) should be updated to focus on the steps that were created for the README.md . Create two sections, "Analytics Data Pipeline" and "Slack Integration Tool". The first section could link to the readme install steps or expand on them. Copy/paste the items from [usage.md](https://github.com/navapbc/simpler-grants-gov/blob/main/documentation/analytics/usage.md#working-with-the-analytics-database) to here, but use the `make` commands instead of the local poetry. The Github token thing might need to be included. [Setting up the tool locally](https://github.com/navapbc/simpler-grants-gov/blob/main/documentation/analytics/development.md#setting-up-the-tool-locally) could be moved under that latter setting so it is clear it is just for the slack integration piece.   `make setup` doesn't exist AFIACT so should be removed. 
- [ ] [usage.md](https://github.com/navapbc/simpler-grants-gov/blob/main/documentation/analytics/usage.md), should be updated so that the new stuff is removed and moved to 'development.md' and the file is renamed to "Usage of Slack Integration"

**Comment by margaretspring** [comment]
@aplybeah - Not sure if it's bc I'm checking this out from the Project view side of things, but it's sorta tricky to tease out what I should be reviewing as new content. It'd be great if you could point to or include links... for example When I tried to check out the [README.md](https://github.com/navapbc/simpler-grants-gov/blob/main/analytics/README.md#simpler-grants-analytics) - The history doesn't indicate any changes. Another example, when I tried to check out the [Technical Overview](https://github.com/navapbc/simpler-grants-gov/blob/main/documentation/analytics/technical-overview.md) & the Orchestration updates - the 1st link went to a[ 404](https://github.com/navapbc/simpler-grants-gov/blob/main/.github/workflows/run-analytics.yml) error.  Is there possibly a draft version that I'm supposed to look at & guidance is provided in the PR version opposed to the Project view of the issue?

**Comment by acouch** [comment]
Issue migrated to hhs/simpler-grants-gov#2130
