### ISSUE TITLE
Opportunity Listing Research Plan

### ISSUE THREAD

**Issue by margaretspring** [navapbc/simpler-grants-gov#132]

**Comment by margaretspring** [comment]
@crystabelrangel - Just created a placeholder for this following our Standup conversation to start with Research Plan to get the ball rolling for both the friends & family testing & when we're back ramping up with HHS. 

I'd like to leverage the approach & look to develop versions of deliverables created for[ NJ UI.](https://navasage.atlassian.net/wiki/spaces/NJUI/pages/512000976/Foundational+Discovery) and this reference from [MA PFML](https://drive.google.com/file/d/1wwo2Y5z7vm4xr8xtz2Dwz9Q8TE9gMNCQ/view)

**Comment by crystabelrangel** [comment]
https://docs.google.com/document/d/1bzchlEotRFpzmKi3Cz20kPSBaqgI3kxV60-kyv979uc/edit?usp=sharing
Here is the research plan

**Comment by acouch** [comment]
Issue migrated to hhs/simpler-grants-gov#2049
