### ISSUE TITLE
[Task]: Setup s3 localstack

### ISSUE THREAD

**Issue by chouinar** [navapbc/simpler-grants-gov#138]
### Summary

We are going to use S3 for storing files that the API returns, and want to be able to use S3 presigned URLs. For local development, we want to be able to have a mocked S3, and localstack is a simple approach for doing that.

**Comment by acouch** [comment]
Issue migrated to hhs/simpler-grants-gov#2046

**Comment by acouch** [comment]
Issue migrated to hhs/simpler-grants-gov#2052
