### ISSUE TITLE
[Task]:  Setup utility for processing response objects and returning them from OpenSearch

### ISSUE THREAD

**Issue by chouinar** [navapbc/simpler-grants-gov#15]
### Summary

We need whatever we turn the response object into to be something our Marshmallow schemas can handle.

Note that raw JSON might be fine, but at the moment Marshmallow would break when trying to serialize the enum fields (it'll try to call `.value` on them) - might need to adjust that logic in some way.

While we won't quite implement actually calling the endpoint, add something very basic as a mock response here to validate the serialization.

**Comment by chouinar** [comment]
Closing in favor of https://github.com/navapbc/simpler-grants-gov/issues/14 as I'll just build them together.

**Comment by acouch** [comment]
Issue migrated to hhs/simpler-grants-gov#2083
