### ISSUE TITLE
Create Grants Research Repository

### ISSUE THREAD

**Issue by margaretspring** [navapbc/simpler-grants-gov#158]

**Comment by margaretspring** [comment]
@crystabelrangel - I do love this idea and would like us to explore gettings something going in Confluence. I've already submitted a Eden ticket for linking this Project to Jira & COnfluence to test-drive what we might pitch to HHS. 

One concern - I'm cautious about calling it a repository. Given that term is used for for code collections ... do we want to risk confusion. Should we call it our Research/Resource Library?? Curious your thoughts.

**Comment by crystabelrangel** [comment]
@margaretspring we can call it Research Index! That's what we're calling the PFML research repo now :)

**Comment by acouch** [comment]
Issue migrated to hhs/simpler-grants-gov#2102
