### ISSUE TITLE
Friends & Family/Work Stoppage Research Plan

### ISSUE THREAD

**Issue by margaretspring** [navapbc/simpler-grants-gov#159]
On 7/16, Margart and I decided to conduct the two Friends and Family studies as discovery-based research to validate previous research.

**Comment by crystabelrangel** [comment]
https://docs.google.com/document/d/1bzchlEotRFpzmKi3Cz20kPSBaqgI3kxV60-kyv979uc/edit?usp=sharing
Here is the research plan

**Comment by acouch** [comment]
Issue migrated to hhs/simpler-grants-gov#2045
