### ISSUE TITLE
[Task]:  Scope out other features we might add to search

### ISSUE THREAD

**Issue by chouinar** [navapbc/simpler-grants-gov#17]
### Summary

After all the prior tickets, this is a placeholder to figure out what else we might want to implement for search that is simple enough with a search index. A few ideas:

- Additional filters
   - Date range (various fields)
- Did you mean
- Synonyms specific to search
- Additional query behavior
   - If you search for "HHS" in the query box, when matching against the agency field, this will only do an exact match. It won't handle "HHS-xyz" automatically for you. You can do "HHS*" but that might not be something everyone knows they can do. We might work around this by indexing the "root agency" as an additional field, or find some other mechanism.

**Comment by acouch** [comment]
Issue migrated to hhs/simpler-grants-gov#2171
