### ISSUE TITLE
[Task]: Fix SearchPagination.tsx to remove inline styling

### ISSUE THREAD

**Issue by btabaska** [navapbc/simpler-grants-gov#170]
### Summary

```
<div
      style={{
        pointerEvents: loading ? "none" : "fill",
        opacity: loading ? 0.5 : 1,
      }}
    >
```
SearchPagination.tsx has inline styling. This is an anti-pattern and needs to be fixed.

### Acceptance criteria

Remove inline CSS styling. Replace with a className based approach

**Comment by acouch** [comment]
Issue migrated to hhs/simpler-grants-gov#2041
