### ISSUE TITLE
[Task]: Refactor SearchResultsListItem.tsx to improve readability

### ISSUE THREAD

**Issue by btabaska** [navapbc/simpler-grants-gov#172]
### Summary

SearchResultListItem.tsx contains a lot of deeply nested DIVs, repeated code and confusing ternary statements. It could be cleaned up to improve readability.

### Acceptance criteria

Refactor SearchResultsListItem.tsx to improve readability

**Comment by acouch** [comment]
Issue migrated to hhs/simpler-grants-gov#2097
