### ISSUE TITLE
[Task]: Modify data import to search index to also work incrementally

### ISSUE THREAD

**Issue by chouinar** [navapbc/simpler-grants-gov#179]
### Summary

The current implementation of the data import to the search index is a full refresh which fully loads all opportunity data again to the search index.

We may want to only make updates/deletes/inserts instead when the dataset becomes larger (eg. when we add support for indexing files). This ticket aims to make the process support an incremental approach as well.

Note that we should maintain the full refresh logic as it may make sense to occasionally fully reload the data anyways.

**Comment by acouch** [comment]
Issue migrated to hhs/simpler-grants-gov#2038
