### ISSUE TITLE
[Task]: Pin version of Python used to a specific minor version

### ISSUE THREAD

**Issue by chouinar** [navapbc/simpler-grants-gov#184]
### Summary

See: https://github.com/navapbc/template-application-flask/pull/235 where details are described - this PR will just mirror these changes.

### Acceptance criteria

- [ ] Python pinned to 3.12
- [ ] Details on how to upgrade Python to 3.13 (and beyond) documented

**Comment by acouch** [comment]
Issue migrated to hhs/simpler-grants-gov#2035
