### ISSUE TITLE
[Task]: Cleanup makefile for opensearch commands

### ISSUE THREAD

**Issue by chouinar** [navapbc/simpler-grants-gov#191]
### Summary

We have a few TODOs in our API makefile regarding the opensearch setup. Now that multiple developers may be using it, we should fix those issues and better document them.

### Acceptance criteria

- [ ] Take a quick look over the makefile and fix inconsistencies

**Comment by acouch** [comment]
Issue migrated to hhs/simpler-grants-gov#2032
