### ISSUE TITLE
[Task]: (Backend) Research field population of the legacy system

### ISSUE THREAD

**Issue by chouinar** [navapbc/simpler-grants-gov#21]
### Summary

We know how many of the fields are populated on the current detail page, but we should verify several specific fields are populated as expected.

A few fields to specifically call out:
* The agency fields (since there are several dupe fields these could be)
* Original closing date
* Version

**Comment by chouinar** [comment]
I believe the HTML is built in `SearchResultsDetail.vue` for future reference. Following that backwards to the opportunity model.

# Original Close Date
This also applies to the original close date description

Legacy logic:
* Only synopsis records (forecasts have no close date themselves)
* If the revision number is null or 0, it assumes its the earliest, and returns that.
* Otherwise finds the earliest history synopsis record and returns its close date.

Thoughts:
* Do we want to consider only returning this if its different? At the very least, the UI should probably only meaningfully display it if it is different.

# Version
Currently displays as either `Synopsis <version>` or `Forecast <version>` based on whether its a forecast.

Version number is separate from revision number (which is a historical-only value) and is never null.

Generally speaking, version number seems to just be calculated as "every time a synopsis or forecast is created, increment by 1" however that would mean it _should_ just be the same as the revision number + 1. However, that doesn't seem to be what happens in all cases. Take this record for example: 
https://grants.gov/search-results-detail/317935

There are only two historical records, yet the version number is in the 60s. How that happened, I have no idea. Normally its just off by 1-2, so this is an extreme example.

# Agency fields
One detail that is useful to know, agency name info is fetched from a view in their system. They literally have a view called `TSYNOPSIS_AGENCY_NAME` (why it starts with a T, I'm not sure? They usually start their views with `V`). This is only used for the name.

When the name is fetched, it uses the agency code from the synopsis, not the opportunity. A quick data analysis of prod data, the values generally match between the two, there are only ~12 that don't match (and most because its not set on the synopsis). One case where it doesn't match can actually be seen, although its very, very minor. https://grants.gov/search-results-detail/345675

The opportunity has an agency of `HHS-ACF-FYSB` and the synopsis has `HHS-ACF`. Search uses the first one when you look for this, but I can be certain that the detail page is using the synopsis value because the name it displays is for `HHS-ACF`. The full name is very slightly different: `Administration for Children & Families` versus `Administration for Children & Families - ACYF/FYSB`. In all honesty, we might just be fine going with the opportunity value always and simplifying this a lot. The existing logic looks like it has a fallback if the synopsis is null anyways.

# Some other values
<table>
<tr><th>UI Element Name</th><th>Our Field Name</th></tr>

<tr><td>Grantor Contact Description</td><td>summary.agency_contact_description - note that they replace any occurrence of \n with < br > Also agency_contact_email + agency_contact_email_description, but it looks like forecasts specifically also adding the agency phone number?</td></tr>
<tr><td>Link to Additional Information</td><td>summary.additional_info_url + summary.additional_info_url_description</td></tr>
</table>


# Miscellaneous
TODOs:
* Document which fields can be HTML based on the ones that have `v-html` tags
* Organize follow-ups / communicate this to frontend/design

**Comment by chouinar** [comment]
Fields that can be HTML (crossed-out fields technically can be, but the data doesn't have them that way):
* ~Opportunity title~
* ~Opportunity category explanation~
* ~Category explanation~
* ~Closing date description~
* Additional Information on Eligibility
* Description

So, seems like its just the last two fields, which is what I assumed.

**Comment by chouinar** [comment]
Summarizing the above:
* Original close date (and its description) is something we could support, would need to add the field + fetch it in the GET endpoint
* Version is based on the version number (+ the is_forecast boolean) returned in the summary object, will need to add that to the response model if we want to keep it
* Agencies are a mess, the agency code is actually used on the detail page, although it almost always matches the agency that is used in search. Some of the other fields appear on the page.
* The agency name itself is still something we'd need to sort out - that isn't from the model, it needs to be loaded differently. This might be something we need to scope out as its own work or do what we did on search and have a mapping there (we might want that for the future for translations anyways?)
* Some fields can contain and expect to be formatted as HTML. Yes, the DB row contains raw HTML.

An example of raw HTML. https://grants.gov/search-results-detail/352579 has a pretty uneventful looking description, but in the DB it looks like:
```html
<p>Note:&nbsp;Each funding opportunity description is a synopsis of information in the Federal Register application notice. For specific information about eligibility, please see the official application notice. The official version of this document is the document published in the Federal Register. Free Internet access to the official edition of the Federal Register and the Code of Federal Regulations is available on GPO Access at: <a href="http://www.access.gpo.gov/nara/index.html" target="_blank">http://www.access.gpo.gov/nara/index.html</a>.&nbsp;Please review the official application notice for pre-application and application requirements, application submission information, performance measures, priorities and program contact information.</p> 
<p><span style="color: rgb(51, 51, 51);">&nbsp;</span></p> 
<p><span style="color: rgb(51, 51, 51);">For the addresses for obtaining and submitting an application, please refer to our Revised Common Instructions for Applicants to Department of Education Discretionary Grant Programs, published in the Federal Register on December 7, 2022.</span></p> 
<p><span style="color: rgb(51, 51, 51);">&nbsp;</span></p> 
<p><span style="color: black;">Purpose of Program:&nbsp;The ANNH Program provides grants to eligible institutions of higher education (IHEs) to enable them to improve and expand their capacity to serve Alaska Native and Native Hawaiian students.&nbsp;Institutions may use these grants to plan, develop, or implement activities that strengthen the institution.</span></p> 
<p><span style="color: rgb(51, 51, 51);">&nbsp;</span></p> 
<p><span style="color: rgb(51, 51, 51);">&nbsp;</span></p> 
<p><span style="color: rgb(51, 51, 51);">Assistance Listing Number (ALN) 84.031N.</span></p> 
<p><span style="color: rgb(51, 51, 51);">&nbsp;</span></p>
```

**Comment by margaretspring** [comment]
@andycochran - @rishalee & @crystabelrangel Saw this during REfinement, but would you huddle up with them to figure out next steps when you're back, Thank you!

**Comment by chouinar** [comment]
https://docs.google.com/spreadsheets/d/163cqQy9SdJIPFOBDwJV9fuqG0xougo0O_QMjl0PFod8/edit#gid=0

**Comment by acouch** [comment]
Issue migrated to hhs/simpler-grants-gov#2085
