### ISSUE TITLE
[Task]: Investigate and implement front end caching

### ISSUE THREAD

**Issue by rylew1** [navapbc/simpler-grants-gov#23]
* Blocked by Initial load/ suspense work https://github.com/HHS/simpler-grants-gov/issues/1804

### Summary

Look into caching at least the initial load.

This is a feature of Next js - but it might not be working?

### Acceptance criteria

- Frontend caches results

**Comment by rylew1** [comment]
There likely also needs to be some timeout/invalidation as api data will be fed updates?

cc @chouinar @acouch

**Comment by acouch** [comment]
@rylew1 do you mean caching the data or [html rendering](https://nextjs.org/docs/app/building-your-application/caching#full-route-cache)?

**Comment by acouch** [comment]
Issue migrated to hhs/simpler-grants-gov#2167
