### ISSUE TITLE
[Task]: Accessibility approach in our product development lifecycle

### ISSUE THREAD

**Issue by sumiat** [navapbc/simpler-grants-gov#28]
### Acceptance Criteria

- [ ] Approach for how we handle accessibility in our product development lifecycle
- [ ] Post for review/incorporate feedback

**Comment by sumiat** [comment]
https://docs.google.com/document/d/1ptLwk55Pdk08N20h2hJPgTiNqNAc44UCxKcrFrYBh-A/edit ready for feedback from engineering and design to align on what's feasible in practice

**Comment by acouch** [comment]
Issue migrated to hhs/simpler-grants-gov#2163
