### ISSUE TITLE
[Task]:  *BLOCKED* - post-deploy e2e tests

### ISSUE THREAD

**Issue by rylew1** [navapbc/simpler-grants-gov#29]
*Blocked* - requires testing in actual non-local environments

### Summary

We currently have tests that spin up the FE and API in github actions and perform "local to local" tests

We also want to have tests that will run post-deploy - so the tests would wait for the deploy to be fully complete, visit that environment and perform the tests. This would give some assurance that the deploy and infra are working (something local-to-local tests don't cover) 

### Acceptance criteria

- post deploy e2e tests running for each env

**Comment by rylew1** [comment]
fyi @chouinar @acouch @coilysiren

**Comment by acouch** [comment]
Issue migrated to hhs/simpler-grants-gov#2162
