### ISSUE TITLE
[Task]: Determine Recruitment Priority

### ISSUE THREAD

**Issue by btabaska** [navapbc/simpler-grants-gov#33]
### Summary

Hold sessions to determine the priority of participants in the hackathon in the event that we reach the event cap and need to decide who to admit.

Draft a document with the output from those sessions that spells out what the criteria will be for admission. It should also have language for pointing people away from this event towards the next one while still thanking them for their participation. This document should consider the persona's of the individuals that we are looking to have participate in this event. 

### Acceptance criteria

A document is drafted that stipulates the criteria for who would receive priority admission to the event. The document spells out why and how we will make that determination.

**Comment by acouch** [comment]
Issue migrated to hhs/simpler-grants-gov#2158
