### ISSUE TITLE
[Task]: Create voice and tone guide for Collaborative Coding Challenge

### ISSUE THREAD

**Issue by btabaska** [navapbc/simpler-grants-gov#35]
### Summary

Host a session to determine voice and tone for communicating with Collaborative Coding Challenge participants. 
The session should discuss:
- Discuss the overall personality and style of communication. Is it formal or informal? Professional or friendly?
- Determine how the voice changes in different contexts, such as social media posts, emails, website content, etc.

The sessions should output:
-  Create templates and examples for different types of communication (e.g., emails, social media posts, website content).
-  Define key messages and value propositions for each persona.
- List dos and don’ts for communicating with each persona.

Create a draft of the voice and tone guide based on the meeting outcomes.

### Acceptance criteria

Create a document that captures the voice and tone that we will be using to communicate with attendees of this challenge

**Comment by acouch** [comment]
Issue migrated to hhs/simpler-grants-gov#2156
