### ISSUE TITLE
[Task]: Draft content for nonexistent page error

### ISSUE THREAD

**Issue by andycochran** [navapbc/simpler-grants-gov#36]
If the user attempts to load a URL for the Search UI with a page query param that does not exist (e.g. `page=999999` or `page=foo`), the results should show an error message in an [error variant Alert component](https://designsystem.digital.gov/components/alert/) that communicates: 
- The requested page does not exist
- The user can navigate to a page that does exist. They might do this by: 
  - Interacting with the pagination menu
  - ~A link in the message that takes them to the first page (which should exist)~ (no need; see comments) 

#### Open Qs: 
- Is interacting with the pagination menu an obvious enough remedy, or should there be a specific call to action (i.e. "go to p1")? 
- @rylew1, can we ensure that this error only displays if p1 would show valid results? We wouldn't want to show this message if the URL has other malformed params that would not return results on p1.

**Comment by rylew1** [comment]
I think the existing pagination menu (if there is search results) - should be enough for the user . They can click page 1 to go to valid results

**Comment by andycochran** [comment]
Agreed. We can also monitor analytics to see if it's a problem. Hopefully very few will see this error.

**Comment by acouch** [comment]
Issue migrated to hhs/simpler-grants-gov#2155
