### ISSUE TITLE
[Task]: Finish e2e tests

### ISSUE THREAD

**Issue by rylew1** [navapbc/simpler-grants-gov#37]
### Summary

They were started here: https://github.com/HHS/simpler-grants-gov/issues/1757

But we need to finish the rest of them to match as many of the bug bash cases as we can https://docs.google.com/spreadsheets/d/1EoBeuiGopBFoI5DRDi3NJ2-Y8lIKMde4RsAaIUmzLC8/edit#gid=0

### Acceptance criteria

- Full set of e2e tests that match bug bash tests

**Comment by acouch** [comment]
Issue migrated to hhs/simpler-grants-gov#2082
