### ISSUE TITLE
[Task]:  Add `make sprint-data-import` and `issue-data-import` to import github sprint and issue data to database

### ISSUE THREAD

**Issue by acouch** [navapbc/simpler-grants-gov#46]
### Summary

From: https://github.com/HHS/simpler-grants-gov/issues/1600

One strategy would be to keep the  `make sprint-data-export` and `issue-data-export` and create  `make sprint-db-data-import` and `issue-data-db-import` so that the data is exported to JSON and then imported into the database.

A single make command could then be created to run the the export and then import files.

Bonus points if there is a way to pipe the Github data directly to the database.

**Comment by aplybeah** [comment]
Update: added `make` command while polishing up work for #45

**Comment by aplybeah** [comment]
Update: work can be tracked on [this branch](https://github.com/navapbc/simpler-grants-gov/tree/import-sprint-data)
There is a bit of loc al testing happening

**Comment by acouch** [comment]
Issue migrated to hhs/simpler-grants-gov#2076

**Comment by acouch** [comment]
Issue migrated to hhs/simpler-grants-gov#2078
