### ISSUE TITLE
[Task]: Search agency name is incorrect

### ISSUE THREAD

**Issue by rylew1** [navapbc/simpler-grants-gov#5]
### Summary

 In the search results, for agency name, you’re using the agency code and/or name from the summary object. We don’t want to do that, that data is junk (I should remove them from the API response entirely), we only want to use the agency in the top-level opportunity object.
 
 
 see slack thread https://nava.slack.com/archives/C057K146W8H/p1715720160675029

### Acceptance criteria

- correct agency info displays

**Comment by acouch** [comment]
Issue migrated to hhs/simpler-grants-gov#2172
