### ISSUE TITLE
[Task]: Switch sort by dropdown to USWDS Select component 

### ISSUE THREAD

**Issue by rylew1** [navapbc/simpler-grants-gov#50]
### Summary

From: https://github.com/HHS/simpler-grants-gov/issues/1637

Switch sortby dropdown to uswds component

**Comment by acouch** [comment]
Issue migrated to hhs/simpler-grants-gov#2075

**Comment by acouch** [comment]
Issue migrated to hhs/simpler-grants-gov#2086
