### ISSUE TITLE
[Task]: Date rounding bug 

### ISSUE THREAD

**Issue by rylew1** [navapbc/simpler-grants-gov#56]
### Summary

From https://github.com/HHS/simpler-grants-gov/issues/1806

Noticing on the UI locally that the dates are off-by-1 (eg. 2023-04-23 is rendering as April 22, 2024)

 

### Acceptance criteria

Dates are not rounding and match API response dates

**Comment by acouch** [comment]
Issue migrated to hhs/simpler-grants-gov#2073
