### ISSUE TITLE
[Task]: For local development, have the swagger UI auto-populate the auth token

### ISSUE THREAD

**Issue by chouinar** [navapbc/simpler-grants-gov#58]
### Summary

Having to retype in the auth token every time is tedious when testing locally.

Seems that Swagger has some support for doing this.
https://swagger.io/docs/open-source-tools/swagger-ui/usage/configuration/
https://stackoverflow.com/questions/45199989/how-do-i-automatically-authorize-all-endpoints-with-swagger-ui
https://apiflask.com/configuration/#swagger_ui_config

**Comment by acouch** [comment]
Issue migrated to hhs/simpler-grants-gov#2072
