### ISSUE TITLE
[Task]: Log pagination repeated clicks

### ISSUE THREAD

**Issue by rylew1** [navapbc/simpler-grants-gov#62]
### Summary

We want to see if people are repeatedly clicking pagination

Can we log each pagination click and somehow correlate when the timestamp difference is less than the pagination debounce time 

- run a query that checks for pagination clicks within a half second

### Acceptance criteria

- GA logging for pagination clicks

**Comment by acouch** [comment]
Issue migrated to hhs/simpler-grants-gov#2149
