### ISSUE TITLE
[Task]: Add original_close_date + original_close_date description to the get opportunity endpoint

### ISSUE THREAD

**Issue by chouinar** [navapbc/simpler-grants-gov#66]
### Summary

Logic from the legacy system:
* Only synopsis records (forecasts have no close date themselves)
* If the revision number is null or 0, it assumes its the earliest, and returns that.
* Otherwise finds the earliest history synopsis record and returns its close date.

**Comment by acouch** [comment]
Issue migrated to hhs/simpler-grants-gov#2148
