### ISSUE TITLE
[Task]: Investigate agency data + structure we might want to use

### ISSUE THREAD

**Issue by chouinar** [navapbc/simpler-grants-gov#71]
### Summary

We do have extracts from the prod table that we were provided before stopping work - so can explore the data a bit.

Out of scope:
* Figuring out where the data comes from

**Comment by chouinar** [comment]
Notes: https://docs.google.com/document/d/1EPZJyqTQruq-BkQoojtrkLqgVl8GrpfsZAIY9T1dEg8/edit

**Comment by acouch** [comment]
Issue migrated to hhs/simpler-grants-gov#2065
