### ISSUE TITLE
[Task]: Have pa11y ci run against a dynamic sitemap

### ISSUE THREAD

**Issue by rylew1** [navapbc/simpler-grants-gov#73]
### Summary

Other projects (like jekyll)  generate a dynamic sitemap - that will update routes as they are added to the frontend.

Some possible options:
- https://nextjs.org/docs/app/api-reference/functions/generate-sitemaps
- https://nextjs.org/learn-pages-router/seo/crawling-and-indexing/xml-sitemaps

Due to 

### Acceptance criteria

- Pa11y ci runs against a sitemap

**Comment by acouch** [comment]
Issue migrated to hhs/simpler-grants-gov#2070
