### ISSUE TITLE
[Task]: Add a pa11y ci step to spin up the API so it shows search results

### ISSUE THREAD

**Issue by rylew1** [navapbc/simpler-grants-gov#74]
blocked by #40 

### Summary

When pa11y tests the search page, it is doing so against just the frontend, and therefore the search page will not have any search results loaded (it will be just the red error alert) - but we want to a11y test against the actual search result list content.

`ci-frontend-a11y.yml` should add a step to load the API (see the `ci-frontend-e2e.yml` file for how to do this - it should be the same exact process)

### Acceptance criteria

- pa11y runs against loaded search results 
- pa11y tests pass

**Comment by rylew1** [comment]
I think we actually want to test against both the red error state, and valid search results state.

**Comment by acouch** [comment]
Issue migrated to hhs/simpler-grants-gov#2147
