### ISSUE TITLE
[Task]: Make search sidebar sticky

### ISSUE THREAD

**Issue by btabaska** [navapbc/simpler-grants-gov#75]
### Summary

Make the search sidebar use the sticky class so that it can be scrolled independently of the results when stuck.

See https://codepen.io/andycochran/pen/BabejWq?editors=1100

This is blocked by [ issue ??? ] to implement the beta alert banner, which also uses sticky. It needs to be in place first to make sure these can both work together.

### Acceptance criteria

- Search sidebar Is sticky

**Comment by acouch** [comment]
Issue migrated to hhs/simpler-grants-gov#2146
