### ISSUE TITLE
[Task]: Frontend built site has minified react errors 

### ISSUE THREAD

**Issue by rylew1** [navapbc/simpler-grants-gov#77]
### Summary

Minified React error 422 and 425

![image](https://github.com/navapbc/simpler-grants-gov/assets/93001277/e1eb5d23-13bc-473e-865a-1d6cc1b2c9c7)

### Acceptance criteria

Fixed minified errors

**Comment by acouch** [comment]
Issue migrated to hhs/simpler-grants-gov#2069
