### ISSUE TITLE
[Task]: Update docker commands based on recent changes

### ISSUE THREAD

**Issue by chouinar** [navapbc/simpler-grants-gov#88]
### Summary

We still have several commands that use `docker-compose` instead of `docker compose`. The approach with a dash was deprecated in 2021, although depending on how you setup your local docker installation, it may be aliased to the latter.

Additionally, a recent version of docker removed the need to add a version to the docker-compose files, which causes a warning message to appear when running docker commands.

### Acceptance criteria

- [ ] Updated docker commands to not contain a dash
- [ ] Updated docker-compose files to not include a version

**Comment by acouch** [comment]
Issue migrated to hhs/simpler-grants-gov#2063
