### ISSUE TITLE
[Task]: Refactor useSearchFilter logic

### ISSUE THREAD

**Issue by sumiat** [navapbc/simpler-grants-gov#93]
### Summary
https://github.com/HHS/simpler-grants-gov/issues/1498

- Started a class in #1491 `SearchFilterManager` that should keep track of the total checked count, the checked count in each section

- maybe rename it to `useSearchFilterAccordion` to be more accurate

- Should the class be in the same file as the custom hook?

### Acceptance criteria

- code in `useSearchFilter` is more organized

**Comment by acouch** [comment]
FYI @rylew1 I think a lot or all `useSearchFilter` might be able to go away with #101 because we don't need to keep track of the state of the selected items.

**Comment by acouch** [comment]
Issue migrated to hhs/simpler-grants-gov#2139
