### ISSUE TITLE
[Task]: Create frontend opportunity listing page

### ISSUE THREAD

**Issue by rylew1** [navapbc/simpler-grants-gov#96]
### Summary

- create new app router page
- setup subclass to `BaseAPI` for new API call (believe we can use v1 endpoint `GET Opportunity`
- Display summary results in table

guide for displaying fields:

https://docs.google.com/spreadsheets/d/163cqQy9SdJIPFOBDwJV9fuqG0xougo0O_QMjl0PFod8/edit#gid=0

### Acceptance criteria

- Basic opportunity summary data showing on page (when you click a result from the search page)

**Comment by acouch** [comment]
Issue migrated to hhs/simpler-grants-gov#2068
