### ISSUE TITLE
[Task]: Fix getRoutes sitemap creation test

### ISSUE THREAD

**Issue by rylew1** [navapbc/simpler-grants-gov#98]
### Summary

`frontend/tests/utils/getRoutes.test.ts`

This test does not properly mock away the `listPaths` function. It just generates the sitemap as the actual site does. 

We need to properly mock this function, provide it with a set of urls (such as in the `getPaths` function) , and see it properly process those urls

**Comment by acouch** [comment]
Issue migrated to hhs/simpler-grants-gov#2136
